; Check https://devguide.python.org/versions/ to see which versions of python to support
; (recommended 'security' and 'bugfix' only)
[tox]
requires =
    tox>=4
env_list = python{3.10,3.11,3.12}

[testenv]
description = run unit tests
basepython =
    ; .package: python3.8
    python3.8: python3.8
    python3.9: python3.9
    python3.10: python3.10
    python3.11: python3.11
    python3.12: python3.12
extras =
    test
commands =
    pytest {posargs}
setenv =
    ; Skips the nondeterministic test in test_tariffs.py
    CI = true
