name: Linting and Testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install bandit[toml]

      - name: Security check - Bandit
        run: |
          bandit -c pyproject.toml -r .

  flake8_py311:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Lint with flake8
        if: always()
        run: |
          pip install flake8
          flake8 . --count --statistics

  black_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

#  mypy_py311:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.11"
#
#      - name: Install Dependencies
#        run: |
#          eval `ssh-agent -s`
#          pip install .[dev]
#
#      - name: Add mypy annotator
#        uses: pr-annotators/mypy-pr-annotator@v1.0.0
#
#      - name: Run mypy
#        run: |
#          mypy src/

  pytest_py310:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download CPLEX installer from Azure storage account
        uses: armanrahman22/azblob-download-action@v0.0.4
        with:
          connection-string: ${{ secrets.BLDDEPS_STORAGE_ACCOUNT_CONN_STR }}
          container-name: "solver-blobs"
          blob-name: "cplex_22.1.1.0-1_amd64.deb"
          download-path: "."

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install .[test]
          # Install CPLEX
          sudo apt install -f ./cplex_22.1.1.0-1_amd64.deb

      - name: Run Pytest
        run: |
          pytest --junit-xml=.test_report.xml
        env:
          OPTIMISER_ENGINE: "cplex"
          OPTIMISER_ENGINE_EXECUTABLE: "/opt/cplex/cplex"
          PYTHONPATH: ./

      - name: Upload Results
        uses: test-summary/action@v1
        with:
          paths: .test_report.xml
        if: always()

  pytest_py311:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download CPLEX installer from Azure storage account
        uses: armanrahman22/azblob-download-action@v0.0.4
        with:
          connection-string: ${{ secrets.BLDDEPS_STORAGE_ACCOUNT_CONN_STR }}
          container-name: "solver-blobs"
          blob-name: "cplex_22.1.1.0-1_amd64.deb"
          download-path: "."

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install .[test]
          # Install CPLEX
          sudo apt install -f ./cplex_22.1.1.0-1_amd64.deb

      - name: Run Pytest
        run: |
          pytest --junit-xml=.test_report.xml
        env:
          OPTIMISER_ENGINE: "cplex"
          OPTIMISER_ENGINE_EXECUTABLE: "/opt/cplex/cplex"
          PYTHONPATH: ./

      - name: Upload Results
        uses: test-summary/action@v1
        with:
          paths: .test_report.xml
        if: always()
