name: Testing and Linting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # This will run ruff, ty and bandit and produce a security report if there are any failures
  linting:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        pyver: ["3.11", "3.12", "3.13", "3.14"]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.pyver }}
      - name: Install Dependencies
        run: uv sync
      - name: Lint (ruff)
        run: uv run ruff check .
      - name: Format check
        run: uv run ruff format --check .
      # To add back in at a later date
      # - name: Typing (ty)
      #   run: uv run ty check .
      - name: Security scan (bandit)
        run: uv run bandit -c pyproject.toml -r src/

  # This will run pytest against the specified version
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download CPLEX installer from Azure storage account
        uses: armanrahman22/azblob-download-action@v0.0.4
        with:
          connection-string: ${{ secrets.BLDDEPS_STORAGE_ACCOUNT_CONN_STR }}
          container-name: "solver-blobs"
          blob-name: "cplex_22.1.1.0-1_amd64.deb"
          download-path: "."
      
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.pyver }}

      - name: Install Dependencies
        run: | 
          uv sync
          sudo apt install -f ./cplex_22.1.1.0-1_amd64.deb

      - name: Run Pytest
        run: uv run pytest -n auto
        env:
          OPTIMISER_ENGINE: "cplex"
          OPTIMISER_ENGINE_EXECUTABLE: "/opt/cplex/cplex"
          PYTHONPATH: ./

